on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Flutter action
      uses: subosito/flutter-action@v1.5.3

    - name: Flutter build
      run: |
        flutter pub get
        flutter build web

    - name: Deploy to GitHub Pages
      run: |
        git clone https://github.com/muhiro12/muhiro12.github.io.git pages
        cd pages/
        cp -r ../build/web/. flutter_playgrounds/
        git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
        git config --local credential.helper ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        git add .
        git commit -m 'Update flutter_playgrounds'
        git push origin HEAD